export const ErrorCodes = {
  AUTH: {
    USER_NOT_FOUND: 'COD_01',
    INVALID_CREDENTIALS: 'COD_02',
    EMAIL_ALREADY_EXISTS: 'COD_03',
    INVALID_TOKEN: 'COD_04',
    INSUFFICIENT_PERMISSIONS: 'COD_06',
  },
  USER: {
    USER_NOT_FOUND: 'COD_01',
    INVALID_DATA: 'COD_07',
    UPDATED_FAILED: 'COD_08',
    DELETE_FAILED: 'COD_09',
    CREATE_FAILED: 'COD_10',
    LOGIN_FAILED: 'COD_11',
  },
  GENERIC: {
    VALIDATION_ERROR: 'COD_12',
    DATABASE_ERROR: 'COD_13',
    UNEXPECTED_ERROR: 'C0D_14',
  },
};
